import AuthContext from "@Components/AuthContext"
import EditModal from "@Components/Modals/EditModal"
import LoginModal from "@Components/Modals/LoginModal"
import RegisterModal from "@Components/Modals/RegisterModal"
import FollowBar from "@Components/layout/FollowBar"
import Sidebar from "@Components/layout/Sidebar"
import "@styles/global.css"
import { Inter } from 'next/font/google'
import { Toaster } from "react-hot-toast"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <AuthContext >
          <Toaster />
          <EditModal />
          <LoginModal />
          <RegisterModal />
          <div className="h-screen bg-black">
            <div className="container h-full mx-auto xl:px-30 max-w-6xl">
              <div className="grid grid-cols-4 h-full">
                <Sidebar />
                <div
                  className="
                  col-span-3 
                  lg:col-span-2 
                  border-x-[1px] 
                  border-neutral-800
              ">
                  {children}
                </div>
                <FollowBar />
              </div>
            </div>
          </div>
        </AuthContext>
      </body>
    </html>
  )
}
